### ISSUE TITLE
Changelog/updates blog

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#106]
File this one under "good PR." We are making a lot of changes to the site, but most users aren't going to engage with us on GitHub to learn about them. GitHub's own blog is a great place to learn about the new stuff they add, so I think setting up a Tumblr or something, that we can link to from the site, would help communicate the cool stuff we do.

If we do choose tumblr, I can help us get that started because that's my house.

**Comment by heydonovan** [comment]
Why not just add a `CHANGELOG.md` file in the root of the project? For example:

https://github.com/docker/docker/blob/master/CHANGELOG.md
https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md
https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md

**Comment by Cantido** [comment]
This wouldn't be for other developers, this would be for users that
wouldn't check out our GitHub. I know Andrew wrote a Medium article for the
data export feature, maybe we could just continue using that, and we add a
"blog" link to the site. Like https://github.com/blog

**Comment by drusepth** [comment]
I think we should have a CHANGELOG.md for us to track what changed (and for me to track changes and promote bits on social media accordingly), but I also like the idea of having a blog for larger releases. We could probably tweet out small releases (as we're doing now) and collect everything that was released each week (or every 2 weeks, or whatever) into a big blog post about "What's new in your Notebook" that details them all.

I've always used Wordpress for things like this, but I think it might make sense to capitalize on the followers we're gaining on Medium for exactly this, since most of the interest relates to Notebook. I can add you guys as collaborators to the Indent Labs collection there (https://medium.com/indent-labs) if you'd like to draft anything up, or you can just pass ideas along through Slack or wherever. :)

**Comment by Cantido** [comment]
I've never used medium, but I'd be happy to get involved. Let me make an
account tonight and I'll let you know. What if, instead of a change log
file, we used GitHubs releases feature, and described changes for each
release there?

**Comment by DarkFieryVortex** [comment]
I just started using Notebook.ai for my writing and it's pretty cool so far. It looked like the site was being updated underneath my feet, which got me curious and led me here. As a user, I would definitely like to see what new features have been added lately and maybe some news about what's coming down the pipe next.

Once it's up and running, it would be nice if you could send out update notifications through the UI. Example: when I login for the first time after a major update, I'd get a simple text bubble in the navigation bar that says, "We rolled out some cool new features!" I click the bubble and it takes me to the blog post.

**Comment by Cantido** [comment]
Thanks for the feedback! That was what I had in mind, too. GitHub does this
for new features and I really like how they do it. I think we would create
Medium articles for new features, since a lot of our user base would
probably be familiar with it.

**Comment by mpigsley** [comment]
Since you all are adding Redcarpet in https://github.com/indentlabs/notebook/pull/124 is there a way to render the `CHANGELOG.md` as a static page and then just link to that page from the nav dropdown by the `Report a problem` link?

You could have the best of both worlds then.
