### ISSUE TITLE
Universe Search

### ISSUE THREAD

**Issue by mpigsley** [indentlabs/notebook#131]
After creating a bunch of locations I've found that I'd really like to do a keyword search through the entire universe. For example, if a city is mentioned in the history of another city or in the backstory of a particular person I'd like to search on that and get that list of resources.

I'd imagine that the search would be limited based on the universe selection in the nav.

**Comment by drusepth** [comment]
I think we definitely want to do in-text linking of content by name (e.g. mentioning City A in the history of City B should link to City A's page in the text by name), which would make this pretty easy to implement the inverse if done properly, I think. 

Since there's a bit of fuzzy matching to match content by name in freeform text, it might be worth doing some cached links on content on saving that content. Here's what I am thinking flow-wise:

1. User saves City B, mentioning City A in City B's history field
2. City B saves successfully, then spawns some kind of asynchronous ContentLinkerTask
3. That task looks through the changed fields on City B, then tries to match any words in the text to other content in the notebook (or more likely, within the current universe). If it finds something to link, it:
  - Replaces "City A" in the field text with something like "[[City A]]" (or some other ID to look up)
  - Adds some TextLink association to City B, with ID "City A" (to look up) and noted field `history`

Then, when someone loads some content's notebook page, we don't have to do in-text matching/linking to notebook content (which could get pretty unwieldy with longer text) and have everything already cached. So as we render each field, we can basically look for TextLinks with that field, then just iterate over each link's ID (e.g. "City A") and do a simple string replacement from the tokenized version (e.g. "[[City A]]"). 

Just a thought on how to do this, I definitely agree that we want to though. :) A lot of other people have requested some way to see reverse links as well (e.g. see all the characters with this location as their hometown), which is similar and also something to do!

**Comment by drusepth** [comment]
Search is live in the newest update, doing basic keyword search across all fields on all content. @mpigsley Want to give it a try?

We can open additional issues for any improvements we'd like from here.
