### ISSUE TITLE
Users have no profile page

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#14]
I've realized that there is no `user_path(@username)` method, because there isn't a profile page for users at all. I'm unable to link authors on content pages for #12 since users don't have a URL to identify them with.

@drusepth Is this intentional?

**Comment by drusepth** [comment]
This is intentional in the sense that I just haven't thought of building it
yet, but it's definitely a good idea. The easier and more intuitive we can
make sharing, I think the better shot we have of the app taking off by word
of mouth.

Feel free to give profile pages a shot, or if you want to leave attribution
out for now, we can just add it after profile pages are added.

**Comment by Cantido** [comment]
I can leave attribute out until I finish #12. I think people would definitely appreciate the branding boost this site could provide if we provide `sameAs` data to point to their other profiles.

**Comment by drusepth** [comment]
Sounds good. I'll throw something together soon, including:

- Author name
- List of their public content
- Link to their website
- Links to their social media accounts
- Where they get inspiration
- Favorite authors
- Favorite books

**Comment by drusepth** [comment]
Path for user profiles is `user_path(@user)`, or implicitly just `@user`, e.g. `link_to "Click me!", current_user`.
