### ISSUE TITLE
Character Quick-Add does not create a character

### ISSUE THREAD

**Issue by mirzokan** [indentlabs/notebook#160]
![quick_add](https://cloud.githubusercontent.com/assets/10578121/19976723/5c7e435e-a1c7-11e6-9995-e1956753caba.gif)

**Comment by Cantido** [comment]
Thank you for reporting this, and thanks for the gif, that's super helpful.

**Comment by drusepth** [comment]
This was my bad. Tried to style the "in-progress" state of the form by adding a `disabled`` class to the input, but rails doesn't pass the value through if the form finishes submitting while it's disabled. 

This should be fixed in https://github.com/indentlabs/notebook/commit/b2837d475907a851ca61090340f76300aa81bc22 and live momentarily. Please reopen this issue if you see it happen again! :+1:
