### ISSUE TITLE
Custom relations

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#201]
We currently allow users to create custom fields and have a text field input for them. 

We should also allow people to create custom relations that populate the relevant dropdown (characters, locations, etc) and allow users to create things like "godfather" fields that let them specify other characters, etc.

Feedback:

>I'd like to link characters to locations, not just as birthplace. It should be generic too, not where they live, as i might have some special case to link someone to that place that isnt related to that.(e.g. Theres a city dedicated to a god, and i want to link that god to the city, but he doesnt actually live there...). This feature goes for a lot of other things. Characters to other characters, locations to locations(a city inside a country, a bar inside a town, etc).

**Comment by Lumireaver** [comment]
Would it also be possible to specify implicated relationships? For instance, could we make it so that every godparent relation implies a reciprocal godchild relation? Further, could Notebook.ai accommodate complex implications? Things like "For any sibling relation, if both siblings have offspring, those offspring are to be regarded as cousins."

Of course those kinds of relations would have to be stripped of their semantic content so as to apply to the greatest audience. (Imagine a fantasy world in which there was a term used to designate a cousin-like relationship shared between pupils of masters who themselves studied under the same master.) 

I don't know how labor intensive any of this is, but I'm willing to learn. I've studied things like formal logic but I've never programmed anything. With that said I might be better poised to learn than a random passerby.

**Comment by drusepth** [comment]
I think specifying implicated relationships (family trees and a master's pupils are great examples) would be a great addition, although I'd want to spend some time in figuring out how to do it fluidly without cluttering up the UI too much (which is doable). 

It'd be a _lot_ easier to hard-code in these fields and rules (similar to how we create parents/sons/daughters/siblings/etc already) based on the inverse, but being able to create these kinds of "rules" for a world would make linking content together much more powerful. 

If you want to fire over to me (andrew@indentlabs.com) with your email, I can shoot you over an invite to Slack and help you get the dev environment set up so you can play around and see what change you can make. :) I'd typically recommend starting with a small bug or two (especially if you are learning programming as you go), but I'd be happy to answer questions on Slack and help out along the way! (Always nice to have more programmers in the world!)

**Comment by derwild** [comment]
I came upon the issue, that there are fields in the "Locations" called "Capital City" for example, but when you want to set them, you can only choose other Locations.
This doesn't make sense to me and also bothers me, because I now have to make a artificial "Location" for each "Town", so I can do the setup correctly, but that reasults in me never using Towns, which is also not really a solution.

I still do not get that choice, but I think this issue here will basically solve the problem (along with some others too) as I can then just have a custom field that links the city.

Because of that I would propose, that in this issue we ONLY change the custom fields to be able to be of any datatype that is available.

@Lumireaver I like your idea, but I think it is better to do things step by step.
My suggestion would be to create a new issue with your ideas, so they can be added in the future and have this issue solved.

@drusepth What do you think?

I think will setup the dev environment in the next days and see if I can implement the change =)

**Comment by drusepth** [comment]
Closing this issue because:

* Fields are now fully customizable. Default fields can be deleted and new fields can be added by users.
* Any field can now link to any kind of page.
