### ISSUE TITLE
Plan Class/Job/Profession

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#202]
From feedback form:

>Classes. Another section where we can describe classes, their requirements, and their function would be a great addition for RPGs!

Not sure what we'd name this so it could apply not only to RPGs and game design, but also writing. Class is the typical term for the former, but perhaps "Profession" might be general enough for everyone? The name matters less after #113, but still useful to get the name right from the get-go. 

Some starting fields (input welcome):

General
* Name
* Classification

Traits
* Advantages/Strengths
* Disadvantages/Weaknesses
* Magic (link to magics)

Resources
* Related items (link to items)
* Resource usage

Job Track
* Demotions (link to jobs, adds the reciprocal relation to its Promotions)
* Promotions (link to jobs, adds the reciprocal relation to its Demotions)
* Specializations (link to jobs)

Links to add to other content:
* Character - `job`
* Location - `jobs_available`
* Group - `jobs`

**Comment by Lumireaver** [comment]
Maybe fields for upgraded positions and downgraded professions along a job track? Or just build the notion of tracks into jobs? (IE: Apprentice Ninja -> Ninja -> Master Ninja, or Adjunct Professor -> Associate Professor -> Tenure Track Professor?)

Or General Super-Professions and Sub Professions/Specializations? (IE: Software Developer -> Notebook.ai Software Developer/Windows Software Developer, or Wizard -> Flame Wizard/Ice Wizard/etc, or Metal Working ->Goldsmithing/Blacksmithing?)

Fields for anthropological stuff. History of the profession? (IE: Nation-ian coal miners unionized in the year WXYZ-AD in order to circumvent harsh taxes which had previously oppressed blah blah blah.) How is the job viewed socially? (IE: Is it restricted to members of higher social castes?) Blurbs about historical figures who exemplify the profession or craft? Things like scientific developments. (IE: If you have "physicist as a job" this field is where you would put years and significant discoveries or inventions. For "artists" you might put developments in the art world like "cubist movement" and such.) As your timeline features develop this would become extra pertinent.

**Comment by Lumireaver** [comment]
Oh, requisite skills and qualifications! IE: Mastery of Dark Magics and Degrees. I don't know if these things would also warrant their own pages. "Skills" works very well for game oriented universes, but "qualifications" is more amenable to a blurb rather than a content link.

**Comment by drusepth** [comment]
That's some great feedback, @Lumireaver; thank you. 

I incorporated some of the job track fields into the original post above and you've got more great feedback on anthropological stuff that still needs incorporated. Until we finish #201 I'm trying to be most thorough with the linking fields, while giving text-based fields more freedom (since users can create their own); looking for a good balance between "enough to get started" and "not too many fields most users won't use". 

Similarly, I'm looking to start on #113 soon which should let us be a lot more active in creating new content types (as specific as we want) without overwhelming users with a ton of content types. I think that'd be a good time to create Skills (which would be very similar to Magic) and link it in. Renaming things like Magic (or even individual fields) is difficult since it renames it for everyone, and it can be a bit jarring to see all the magic in your notebook suddenly renamed to "Skills". Hopefully being able to create Magic _or_ Skills eventually (and choosing one, neither, or both to use) will help alleviate that a lot. Love the "Proficiencies" name though, and it ties in with professions as well. 

Wonderful feedback; I wish I could implement it all today!

**Comment by Lumireaver** [comment]
Thanks for the response. I'm happy to help in any way that I can. I'm kinda flattered because I find this project of yours to be kind of really awesome.

I see what you mean about renaming. It would be one thing if "Magic" was always skill based, but some fictional universes might use "Magic" in an altogether different way. That was a bit short sighted of me.

**Comment by drusepth** [comment]
Planning Jobs is done & live, with customizable fields.
