### ISSUE TITLE
Sub-races and super-races

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#215]
Similar to Groups, we should have derivative (and inverse) races that automatically create the reciprocal relation. Not sure whether to call them sub-races and super-races or derivative races and parent races, or what, but shouldn't be hard to implement once we decide.

Feedback:

>The ability to have sub-races would be neat. For instance, ""Trolls"" might play a large role in your world, but differences between Cave Trolls and Forest Trolls might be significant enough to warrant different entries.

**Comment by drusepth** [comment]
@Lumireaver Do you have any thoughts on good names for these relationships? :)

**Comment by Lumireaver** [comment]
@drusepth Hm, if you're only looking for a name I think the "Parent"/"Child" and "Sibling" tags succeed in designating cultural ancestry and lineage well. Sincerely though, I do not believe that relating races in that way is the most useful way to go about it. I tend to over think things, and I'm still collecting my thoughts on the matter—but I recommend making Races rely upon Creature content in order to express relations to other races.

For example, "Creature/Human" could list "Race/Highlander," "Race/Frostwalker," and so on, associated with it. Benefits of this schema include avoiding commitment to a system that implies racial primacy or superiority. I mean as responsible world builders we'll obviously entertain the idea of a racist race, but we don't need to build racism into our schema as a central and unavoidable element. 

Within "Races" you could have smaller cultural subgroups. "Subcultures" or "Tribes", if necessary.

Essentially I'm recommending the use of "Creatures" for taxonomic organization and "Races" for self-declared ethnicities/cultures. For interplanetary or fantastic settings, multiple creatures could be assigned to a race. 

Don't quote me on this. Race is another tricky subject.

**Comment by lloyd094** [comment]
Without going into too much detail, I think Parent/Child/Sibling relationships works the best, especially if coming from a database environment or genealogy.

I for one would use this feature, as there are only a few parent races in my world. The rest are derivatives thereof, so depending on how universes may be set up, this could be useful. I would however recommend making this an optional feature (or blank) for people who wouldn't use this.

**Comment by drusepth** [comment]
This is done & live, and users can create their own fields to link to other pages also.
