### ISSUE TITLE
Can't run local install?

### ISSUE THREAD

**Issue by lloyd094** [indentlabs/notebook#237]
### Expected behavior
Loading up the webserver, I can reach the homepage and sign in (is there a way to disable for offline or something? That would be fancy). I would expect to be able to either "make an account" or something.

### Actual behavior
Instead of the website allowing me to make an account or sign in with something randomly (or allow me to just go to it...), I get the following error:

```shell
Started GET "/users/sign_up" for 127.0.0.1 at 2017-10-03 17:24:08 -0700
Processing by RegistrationsController#new as HTML
  Rendered devise/registrations/new.html.erb within layouts/application (23.1ms)
Completed 500 Internal Server Error in 32ms (ActiveRecord: 0.0ms)

ActionView::Template::Error (undefined method `email_updates' for #<User:0x007f1f5807e710>
Did you mean?  email_was):
    60:       %>
    61:
    62:       <div class="field">
    63:         <%= f.check_box :email_updates %>
    64:         <%= f.label :email_updates do %>
    65:           We're always working to improve Notebook.ai. Please leave this box checked if you'd like to receive occasional updates about
    66:           what's new.
  app/views/devise/registrations/new.html.erb:63:in `block in _app_views_devise_registrations_new_html_erb__1051671099465407350_69886212280640'
  app/views/devise/registrations/new.html.erb:3:in `_app_views_devise_registrations_new_html_erb__1051671099465407350_69886212280640'
  app/controllers/registrations_controller.rb:5:in `new'
```

### Steps to reproduce the behavior
Follow the steps provided on readme.

**Comment by drusepth** [comment]
I think this is the result of the database not migrating properly (#236) since `email_updates` is a column added to the User table. Re-running `rake db:migrate` should fix this. I also added one other rake task to run for setup to the readme (`rake data_migrations:create_default_billing_plans`) that is needed for some billing functionality (like viewing the billing settings page). 

Sorry for all the bumps setting this up -- let me know if this works after migrating or if you run into any other issues!

**Comment by lloyd094** [comment]
Fixed - thank you!

**Comment by lloyd094** [comment]
Fixed - thank you!
