### ISSUE TITLE
AWS::S3::Errors::InvalidAccessKeyId 

### ISSUE THREAD

**Issue by lloyd094** [indentlabs/notebook#239]
### Expected behavior
When creating a new world, I made a title, a little info, and a picture. Then I clicked save.

### Actual behavior
```bash
Completed 500 Internal Server Error in 9691ms (ActiveRecord: 140.2ms)

AWS::S3::Errors::InvalidAccessKeyId (The AWS Access Key Id you provided does not exist in our records.):
  app/controllers/content_controller.rb:180:in `block in upload_files'
  app/controllers/content_controller.rb:167:in `each'
  app/controllers/content_controller.rb:167:in `upload_files'
  app/controllers/content_controller.rb:120:in `create'
```
Upon going back and refreshing my main screen, the universe shows up but there is no picture, leading me to guess that Pictures are directed somewhere non-existent?

### Steps to reproduce the behavior
Follow the instructions on ReadMe, sign up, create a new world, and save.

**Comment by drusepth** [comment]
Howdy again! This happens because uploading files actually uploads to AWS's S3, which is something I pay for so I don't distribute the credentials (as anyone could then charge as much as they'd like to it). This means everything _except_ image uploads should work fine locally, but if you'd like to enable them you can create your own S3 bucket on AWS (it'd be less than a penny per month for personal use, and I think opening a new AWS account even gives you $100 credit for the first year) and then just set Notebook.ai's AWS access key to your credentials. 

The environment variables you'll want to set for them are `ENV['S3_BUCKET_NAME']` to point to the name of your S3 bucket, and `ENV['AWS_ACCESS_KEY_ID']` / `ENV['AWS_SECRET_ACCESS_KEY']` for your access credentials. You can see how these are used in config/environments/development.rb (or config/environments/production.rb). 

Does that help?

**Comment by lloyd094** [comment]
That makes a lot of sense - everything else does indeed seem to be working outside of pictures. In the event of wanting to run solely local, is there a way to map pictures to a specific directory?

**Comment by mpigsley** [comment]
Yeah, if there is environment specific configuration it wouldn't be too big a change to just read/write to the file system when developing and then switch to using azure in production.

**Comment by drusepth** [comment]
Rails 6 introduces ActiveStorage, that lets you switch between different storage providers (like S3 and local folders). There's an example of it being used on user avatars, and a PR migrating from our current S3-specific setup to using ActiveStorage would be much appreciated (and would make uploading locally possible)!
