### ISSUE TITLE
Divine Artefacts. 

### ISSUE THREAD

**Issue by GreyJack** [indentlabs/notebook#286]
### Expected behaviour
Being able to choose Deities as the owners and makers of Items in the "History" category, for items with a divine origin.
### Actual behaviour
The only options for past, present, and original owners, as well as makers, are Characters.

**Comment by drusepth** [comment]
I'll tackle this this week. :+1: Thanks!

**Comment by drusepth** [comment]
We're moving away from hardcoded linking fields to something more dynamic. As of right now, it's possible to create a "Deities" custom field and link deities with it (instead of providing one by default), so I'm going to mark this issue done. Feel free to reopen if you're having any issues with it though!
