### ISSUE TITLE
Uploading on Self-Hosted Instance

### ISSUE THREAD

**Issue by thetrumper** [indentlabs/notebook#353]
When I attempt to upload an image on my notebook instance the image does not load correctly and when attempting to follow the image, it leads to a "You don't have permission to view that content." message. (https://imgur.com/a/eEkGMLU)

Also, prior to restarting the server when attempting to do this, it would pop up with a red screen talking about "No route matches"

**Comment by drusepth** [comment]
Have you set up an Amazon S3 login to upload images to? We pay for one at www.notebook.ai, but historically developers have just used personal or staging buckets when working on images locally. 

When you have a bucket you want to upload to, you should be able to hook image uploading up by specifying a few environment variables. You can see the config/environments/production.rb file at the end for how this is done and which environment variables you'll need:

```
  # S3 settings for Paperclip uploads
  config.paperclip_defaults = {
    storage: :s3,
    s3_credentials: {
      bucket:            ENV.fetch('S3_BUCKET_NAME',        'notebook-content-uploads'),
      s3_region:         ENV.fetch('AWS_REGION',            'us-east-1'),
      access_key_id:     ENV.fetch('AWS_ACCESS_KEY_ID'),
      secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY')
    }
  }
```

This config block isn't in config/environments/development.rb, so if you're running in development mode locally you can either just switch to production mode, or just copy-paste the block over to the development.rb config file also for the same effect.

**Comment by thetrumper** [comment]
I have not set up an S3 login.

Is there a way to store the images locally on the server? Or is an S3 bucket required?

**Comment by drusepth** [comment]
We use the `paperclip` gem for file uploads and it supports local file storage (I believe), but storing things locally hasn't been implemented. Looks like someone would need to implement it with some config that lets you choose whether to use S3 or the local filesystem. 

I _think_ S3 offers a free tier (or at least a bunch of free credits to new users) at https://aws.amazon.com/free/, so if you're interested in digging in and setting your own up, that might be a low barrier-of-entry way to start exploring. A bucket there is basically just a folder that you can upload/download files from, so the gist is you'd:

1. Sign up for an AWS / S3 account
2. Create a bucket (folder) on S3
3. Get your S3 access credentials and plug them into the notebook.ai config
4. Restart the notebook.ai server for the config changes to take effect

Happy to help if needed :)

**Comment by thetrumper** [comment]
I found a tool called [Minio](https://min.io/) where I can essentially host my own S3 server, which would allow me to use the server for hosting my own images (for free yay!) while still being able to use the way notebook is setup for S3.

I have my server setup at 192.168.1.112:9090 and have a bucket called "notebook." If I upload a file through the minio web interface to the notebook bucket, I can access that file at 192.168.1.112:9090/notebook/FILENAME.

I've researched using paperclip with minio and the general consensus seems to be to have the configuration setup in production.rb look like this:

```
  config.paperclip_defaults = {
  storage: :s3,
  s3_protocol: ':https',
  s3_permissions: 'public',
  s3_region: 'us-east-1',
  s3_credentials: {
    bucket: 'notebook',
    access_key_id: 'mykey',
    secret_access_key: 'mysecretkey',
  },
  s3_host_name: '192.168.1.112:9090',
  s3_options: {
    endpoint: "https://192.168.1.112:9090", # for aws-sdk
    force_path_style: true # for aws-sdk (required for minio)
  },
  url: ':s3_path_url'
  path: "/:class/:id.:style.:extension"
}
```
The problem comes when I actually go to upload and then view the picture in the gallery for the universe I'm creating. After uploading, I get the same broken picture box and the link is "http://192.168.1.112:3000/plan/universes/:s3_path_url?1554857665" (It's normally :s3_domain_url from config/initializers/paperclip.rb but I changed it to :s3_path_url because I think minio is required to use path-style?) Either way, as you can see that ":s3_path_url" doesn't change in the link and I think that's a large problem of why it's not loading properly. Or maybe that's how its supposed to be and the problem is something else. 

Regardless, I'm having trouble getting it to upload and view and was hoping you might be able to help me pinpoint where the issue is.

**Comment by thetrumper** [comment]
So it turns out I was editing production.rb instead of development.rb and so none of my changes were actually having any effect.

I am now at a new issue though, as with those settings when I go to upload a picture the page kind of freezes and the console is stuck at
```
[paperclip] saving content/uploads/original/4e5e990f-2dd8-4e74-a366-a98        d69494457.png
```
Eventually, the page comes up with this: https://imgur.com/a/Q0FxX0y

Also, the link for the broken picture that I still had uploaded is now this: http://192.168.1.112:3000/images/:http://192.168.1.112:9090/notebook/content/uploads/hero/f2d15a58-f17e-4aad-90d2-c0f585df4ce4.png?1554892458

I understand that since this isn't actual S3 this isn't really your issue and doesn't display anything necessarily wrong with notebook, but I'm wondering if you had some insight that could help me fix thiss

**Comment by drusepth** [comment]
@thetrumper Interesting! Sorry for the delay. 

After your updates, it looks like you're still seeing the `Seahorse::Client::NetworkingError execution expired` error, right? According to [this thread](https://github.com/aws/aws-sdk-ruby/issues/904), I have two theories on why you might be getting it:

1. Your file is sufficiently large enough and/or your network is sufficiently slow enough and/or Minio is receiving sufficiently slow enough that the upload is taking longer than Rails allows for processing a request. Is the upload finishing when you see this error? To narrow this down, you could try uploading a smaller file and/or increasing the default Rails response time limit (I think it's 30 seconds by default, but a quick Google should show you where/how to reconfigure that).

2. The domain/endpoint you're trying to upload to is invalid in some way. The linked thread shows this error when someone typo'd the availability zone in S3 resulting in an attempted upload to `ec2.us-west-2a.amazonaws.com` (which doesn't exist) instead of `ec2.us-west-2.amazonaws.com` (which exists). You can probably narrow this down by finding out the exact URL you're uploading to (probably in the `development` file in `logs/`) and verifying that it's correct. You can also try doing a manual upload by command line if you're comfortable playing around with e.g. cURL to simulate what your local server is doing. 

It does definitely look like some kind of networking issue, though. Either not initially connecting to the Minio servers correctly, potentially not authenticating correctly if it is connecting (though I would expect that to throw a more specific error than a general NetworkingError!), or timing out and/or being interrupted in the actual upload.

**Comment by thetrumper** [comment]
Thank you for the help!

I looked at that thread and It's not the zone (also the exact URL isn't displayed in logs/) All it shows is 
` [paperclip] saving content/uploads/original/912d6fb2-0db6-4406-a7f8-202179907736.png ` with no URL.

I did manage to get it to work by using my home's public ip and forwarding the port I use for minio. I'd prefer it if I could use the local ip though since my server isn't secure, so if you can think of any reason why it would work with using the public ip and forwarding the port but not using the local ip address, I'd appreciate any help you can offer :)

**Comment by drusepth** [comment]
Glad it seems you got everything sorted out!

I'm not sure why photos didn't originally work in the original configuration, but I'd guess it just had something to do with a mismatch in config somewhere (possibly on my part also). 

For anyone else wondering in the future, you can modify a user's upload bandwidth by just editing the `upload_bandwidth_kb` property on that user.

I'm closing this issue to keep the issues here clean, but feel free to reopen (or open a new one) if you have any other issues. 👍
