### ISSUE TITLE
How to unlock localhost environment?

### ISSUE THREAD

**Issue by tbirrell** [indentlabs/notebook#531]
I have my local environment all set up, but the application is still locked down. I assumed I could go into billing and change things, but I'm getting the following error on `/my/billing/subscription`:

> NoMethodError in SubscriptionsController#new
> undefined method `invoices' for #<Stripe::Customer:0x00007fbbb4d994b0> Did you mean? invoice_prefix`
> app/controllers/subscriptions_controller.rb:20:in 'new'

Is this what I need to fix? If not, where do I need to go to unlock the local application?

**Comment by drusepth** [comment]
Hmm, this looks like an error with the Stripe gem. However, you should be able to bypass needing that page completely by either manually setting your user to a Premium plan or modifying the authorizers directly. For the former option, you'll want to run the `create_default_billing_plans` rake task (run `rake -T` to list all available tasks so you can find it) and then modify your user's `selected_billing_plan_id` to one of those created BillingPlans. For the latter option, you can [check out the authorizers directory](https://github.com/indentlabs/notebook/tree/master/app/authorizers) and short-circuit whatever you want by just returning `true` instead of checking the actual logic.

**Comment by tbirrell** [comment]
I have Stripe 5.10.0 installed.

Updating the DB by hand did the trick though, so thanks!

**Comment by drusepth** [comment]
Good to hear! I'll take a look and see how 5.10.0 compares to prod, thanks for letting me know.
