### ISSUE TITLE
You can see the name of items/characters/etc.. that you don't have access to 

### ISSUE THREAD

**Issue by eyadfareh** [indentlabs/notebook#863]
### Expected behavior
when linking to an item using @ it shouldn't give you a text like [[Universe-xxxxx]]  instead it should give you a tag with the name.
and the server shouldn't trust the text before checking for permission  
### Actual behavior
it gives you a text [[Universe-xxxx]] that the server trust without checking for permission
### Steps to reproduce the behavior
1. link to an item using @
2. change the number in the text 
3. go to the view page it will give you the name of the item that you don't have access to

**Comment by drusepth** [comment]
Hey, thanks for opening this. This is actually by design to make collaboration easier -- if someone makes a page private, the name appears greyed out so you know what page it used to link to, but the link no longer works and the only visible information from that page is just the page name.

I can see how some people would want to keep page names completely private as well, so I'd be open to a PR adding a server-level configuration option for choosing whether to grey out names that the user doesn't have access to view or redact them entirely!
