### ISSUE TITLE
Document text-only mode: show Object name instead of [[Group-Key]]

### ISSUE THREAD

**Issue by ironjan** [indentlabs/notebook#881]
### Expected behavior

The plain text view should either 
 * show the object's name or 
 * a link as with other links (`link text ( url )`).

### Actual behavior

Currently, the link code `[[Group-Key]]` is shown. 

### Steps to reproduce the behavior

 * Edit a document and switch to the plain text view, e.g. https://www.notebook.ai/documents/125045/plaintext

----

This issue was also mentioned in #863:
> when linking to an item using @ it shouldn't give you a text like [[Universe-xxxxx]] instead it should give you a tag with the name.

**Comment by drusepth** [comment]
This is definitely a bug and should be a quick fix. Thanks for pointing it out. 

I'm leaning towards just replacing the token with the object's name, since it's a plaintext view that'd probably be printed (probably?) and therefore it isn't as important (and might even be disruptive) to have the link. Do you think that sounds reasonable?

**Comment by ironjan** [comment]
Hi Andrew,

Sounds good. The object name is the most important info there.

Based on your point, I'd even suggest to remove the regular links too, i.e.
just show `text` instead of `text ( link )` or replace them with endnotes
(print `text (number)` and add a sorted list at the end of the document).




Andrew Brown <notifications@github.com> schrieb am Do., 4. März 2021, 01:21:
